// Auto-generated by Windjammer — do not edit manually.
// Rust tests in `tests/*.rs` are discovered automatically (no manual `tests/lib.rs` registration).

#[cfg(test)]
pub mod ambiguous_reexports_test;
#[cfg(test)]
pub mod analyzer_auto_mutability_compound_test;
#[cfg(test)]
pub mod analyzer_auto_mutability_method_test;
#[cfg(test)]
pub mod analyzer_auto_mutability_test;
#[cfg(test)]
pub mod analyzer_field_method_mutation_test;
#[cfg(test)]
pub mod analyzer_method_call_mut_propagation_test;
#[cfg(test)]
pub mod analyzer_ownership_control_flow_test;
#[cfg(test)]
pub mod analyzer_ownership_params_test;
#[cfg(test)]
pub mod analyzer_ownership_trait_generic_test;
#[cfg(test)]
pub mod analyzer_self_mutability_inference_test;
#[cfg(test)]
pub mod analyzer_self_receiver_inference_test;
#[cfg(test)]
pub mod analyzer_storage_comprehensive_tests;
#[cfg(test)]
pub mod analyzer_string_field_assignment_test;
#[cfg(test)]
pub mod analyzer_traits_comprehensive_tests;
#[cfg(test)]
pub mod array_element_copy_ownership_test;
#[cfg(test)]
pub mod array_index_copy_type_test;
#[cfg(test)]
pub mod array_index_ownership_test;
#[cfg(test)]
pub mod array_indexing_i32_test;
#[cfg(test)]
pub mod array_literal_codegen_test;
#[cfg(test)]
pub mod asi_paren_integration_test;
#[cfg(test)]
pub mod assignment_type_inference_test;
#[cfg(test)]
pub mod ast_builders_tests;
#[cfg(test)]
pub mod auto_borrow_methods_test;
#[cfg(test)]
pub mod auto_clone_loop_and_partial_move_test;
#[cfg(test)]
pub mod auto_clone_method_receiver_test;
#[cfg(test)]
pub mod auto_deref_regression_test;
#[cfg(test)]
pub mod auto_derive_comprehensive_tests;
#[cfg(test)]
pub mod auto_derive_copy_string_field_test;
#[cfg(test)]
pub mod auto_derive_trait_object_field_test;
#[cfg(test)]
pub mod auto_import_generation_test;
#[cfg(test)]
pub mod auto_mut_borrow_arg_test;
#[cfg(test)]
pub mod auto_ref_deref_copy_test;
#[cfg(test)]
pub mod auto_ref_method_args_test;
#[cfg(test)]
pub mod auto_ref_test;
#[cfg(test)]
pub mod auto_self_inference_test;
#[cfg(test)]
pub mod auto_to_string_test;
#[cfg(test)]
pub mod binary_ops_3layer_test;
#[cfg(test)]
pub mod block_semicolon_test;
#[cfg(test)]
pub mod borrow_break_as_ref_test;
#[cfg(test)]
pub mod borrow_context_no_clone_test;
#[cfg(test)]
pub mod borrowed_field_clone_test;
#[cfg(test)]
pub mod borrowed_iter_copy_field_test;
#[cfg(test)]
pub mod borrowed_string_as_str_test;
#[cfg(test)]
pub mod borrowed_string_parameter_generation_test;
#[cfg(test)]
pub mod bug_astar_break_test;
#[cfg(test)]
pub mod bug_auto_borrow_collision_test;
#[cfg(test)]
pub mod bug_auto_clone_nested_call_then_struct_test;
#[cfg(test)]
pub mod bug_clamp_float_args_match_receiver_test;
#[cfg(test)]
pub mod bug_copy_field_to_le_bytes_owned_param_test;
#[cfg(test)]
pub mod bug_crate_import_build_prefix_test;
#[cfg(test)]
pub mod bug_cross_crate_borrowed_method_call_test;
#[cfg(test)]
pub mod bug_cross_module_owned_arg_test;
#[cfg(test)]
pub mod bug_e0204_copy_derive_non_copy_field_test;
#[cfg(test)]
pub mod bug_e0277_hashmap_self_field_test;
#[cfg(test)]
pub mod bug_e0277_self_field_hashmap_test;
#[cfg(test)]
pub mod bug_e0308_borrowed_struct_field_test;
#[cfg(test)]
pub mod bug_e0308_clone_to_ref_test;
#[cfg(test)]
pub mod bug_e0308_field_assign_ref_test;
#[cfg(test)]
pub mod bug_e0596_if_let_reassign_mutate_test;
#[cfg(test)]
pub mod bug_e0596_self_mutation_inference_test;
#[cfg(test)]
pub mod bug_enum_variant_consumes_param_test;
#[cfg(test)]
pub mod bug_extern_fn_auto_borrow_test;
#[cfg(test)]
pub mod bug_extern_fn_ownership_test;
#[cfg(test)]
pub mod bug_extern_fn_pub_test;
#[cfg(test)]
pub mod bug_extern_fn_string_expr_arg_test;
#[cfg(test)]
pub mod bug_extern_fn_string_to_ffi_no_borrow_test;
#[cfg(test)]
pub mod bug_f32_f64_explicit_cast_test;
#[cfg(test)]
pub mod bug_float_method_ambiguity_test;
#[cfg(test)]
pub mod bug_for_in_self_partial_move_test;
#[cfg(test)]
pub mod bug_hashmap_get_match_arm_deref_test;
#[cfg(test)]
pub mod bug_hashmap_get_mut_tuple_match_test;
#[cfg(test)]
pub mod bug_hashmap_get_node_string_borrowed_test;
#[cfg(test)]
pub mod bug_hashmap_string_key_test;
#[cfg(test)]
pub mod bug_if_without_else_unit_test;
#[cfg(test)]
pub mod bug_index_assign_stores_param_test;
#[cfg(test)]
pub mod bug_index_owned_method_receiver_test;
#[cfg(test)]
pub mod bug_is_stored_enum_option_test;
#[cfg(test)]
pub mod bug_let_method_mut_inference_test;
#[cfg(test)]
pub mod bug_library_index_owned_method_receiver_test;
#[cfg(test)]
pub mod bug_local_readonly_method_not_mut_borrow_test;
#[cfg(test)]
pub mod bug_match_arm_string_no_double_convert_test;
#[cfg(test)]
pub mod bug_match_self_option_field_test;
#[cfg(test)]
pub mod bug_metadata_borrowed_param_ownership_test;
#[cfg(test)]
pub mod bug_method_mut_inference_test;
#[cfg(test)]
pub mod bug_method_return_binary_float_test;
#[cfg(test)]
pub mod bug_method_self_by_value_test;
#[cfg(test)]
pub mod bug_module_string_borrow_call_test;
#[cfg(test)]
pub mod bug_multi_arg_borrow_symmetry_test;
#[cfg(test)]
pub mod bug_multifile_self_field_mutation_test;
#[cfg(test)]
pub mod bug_multipass_ownership_test;
#[cfg(test)]
pub mod bug_multipass_self_ownership_convergence_test;
#[cfg(test)]
pub mod bug_mut_reborrow_codegen_test;
#[cfg(test)]
pub mod bug_mut_self_calls_readonly_method_test;
#[cfg(test)]
pub mod bug_nested_field_access_test;
#[cfg(test)]
pub mod bug_nested_field_borrowed_test;
#[cfg(test)]
pub mod bug_nested_field_method_auto_borrow_test;
#[cfg(test)]
pub mod bug_no_manual_unsafe_extern_test;
#[cfg(test)]
pub mod bug_no_to_string_literal_leakage_test;
#[cfg(test)]
pub mod bug_option_binding_ref_to_owned_test;
#[cfg(test)]
pub mod bug_option_unwrap_borrow_test;
#[cfg(test)]
pub mod bug_ownership_inference_passthrough_test;
#[cfg(test)]
pub mod bug_param_field_method_no_mut_test;
#[cfg(test)]
pub mod bug_passthrough_method_call_test;
#[cfg(test)]
pub mod bug_phase2_stable_override_mismatch_test;
#[cfg(test)]
pub mod bug_println_bool_test;
#[cfg(test)]
pub mod bug_quest_objective_test;
#[cfg(test)]
pub mod bug_quest_state_test;
#[cfg(test)]
pub mod bug_redundant_as_str_test;
#[cfg(test)]
pub mod bug_retain_closure_deref_test;
#[cfg(test)]
pub mod bug_self_field_method_call_mut_inference_test;
#[cfg(test)]
pub mod bug_self_subfield_copy_read_test;
#[cfg(test)]
pub mod bug_snapshot_returns_self_type_not_owned_test;
#[cfg(test)]
pub mod bug_some_wrap_auto_clone_test;
#[cfg(test)]
pub mod bug_stale_game_metadata_overwrites_engine_test;
#[cfg(test)]
pub mod bug_static_method_call_int_cast_test;
#[cfg(test)]
pub mod bug_std_strings_parse_api_test;
#[cfg(test)]
pub mod bug_std_strings_scene_parser_test;
#[cfg(test)]
pub mod bug_string_clone_to_string_test;
#[cfg(test)]
pub mod bug_string_coercion_test;
#[cfg(test)]
pub mod bug_string_comparison_deref_test;
#[cfg(test)]
pub mod bug_string_comparison_explicit_str_ref_test;
#[cfg(test)]
pub mod bug_struct_builder_max_not_f64_test;
#[cfg(test)]
pub mod bug_struct_field_auto_clone_test;
#[cfg(test)]
pub mod bug_struct_literal_string_param_reuse_test;
#[cfg(test)]
pub mod bug_test_target_detection;
#[cfg(test)]
pub mod bug_to_gpu_buffer_not_mut_borrow_test;
#[cfg(test)]
pub mod bug_trait_impl_cross_file_meta_test;
#[cfg(test)]
pub mod bug_trait_impl_cross_file_self_mut_test;
#[cfg(test)]
pub mod bug_transitive_field_mut_inference_test;
#[cfg(test)]
pub mod bug_transitive_self_mut_orchestrator_test;
#[cfg(test)]
pub mod bug_typed_int_literal_test;
#[cfg(test)]
pub mod bug_untyped_let_string_ascription_test;
#[cfg(test)]
pub mod bug_usize_with_capacity_cast_clone_test;
#[cfg(test)]
pub mod bug_vec_push_spurious_clone_test;
#[cfg(test)]
pub mod bug_vec_remove_usize_no_ref_test;
#[cfg(test)]
pub mod bug_vec_string_index_clone_test;
#[cfg(test)]
pub mod build_system_ffi_deps_test;
#[cfg(test)]
pub mod build_system_relative_paths_test;
#[cfg(test)]
pub mod build_system_stale_cargo_toml_test;
#[cfg(test)]
pub mod build_system_test_module_gating_test;
#[cfg(test)]
pub mod cache_locality_analysis_test;
#[cfg(test)]
pub mod cache_management_test;
#[cfg(test)]
pub mod cast_plus_int_fix_test;
#[cfg(test)]
pub mod cast_with_auto_ref_test;
#[cfg(test)]
pub mod cfg_decorator_test;
#[cfg(test)]
pub mod chained_call_mutation_false_positive_test;
#[cfg(test)]
pub mod circle_aabb_type_consistency_test;
#[cfg(test)]
pub mod cli_lint_test;
#[cfg(test)]
pub mod cloned_iter_copy_field_test;
#[cfg(test)]
pub mod codegen_arm_string_analysis_test;
#[cfg(test)]
pub mod codegen_ast_utilities_test;
#[cfg(test)]
pub mod codegen_auto_modules_test;
#[cfg(test)]
pub mod codegen_cast_precedence_test;
#[cfg(test)]
pub mod codegen_closures_comprehensive_tests;
#[cfg(test)]
pub mod codegen_constant_folding_test;
#[cfg(test)]
pub mod codegen_copy_type_arg_test;
#[cfg(test)]
pub mod codegen_copy_type_method_arg_test;
#[cfg(test)]
pub mod codegen_copy_type_no_clone_test;
#[cfg(test)]
pub mod codegen_cross_module_signature_test;
#[cfg(test)]
pub mod codegen_dialog_comprehensive_test;
#[cfg(test)]
pub mod codegen_dialog_ownership_inference_test;
#[cfg(test)]
pub mod codegen_dialog_pattern_test;
#[cfg(test)]
pub mod codegen_dialog_remaining_issues_test;
#[cfg(test)]
pub mod codegen_ensures_param_access_test;
#[cfg(test)]
pub mod codegen_enum_copy_derive_test;
#[cfg(test)]
pub mod codegen_enumerate_no_double_iter_test;
#[cfg(test)]
pub mod codegen_expression_helpers_test;
#[cfg(test)]
pub mod codegen_fixed_array_in_struct_test;
#[cfg(test)]
pub mod codegen_float_binary_op_inference_test;
#[cfg(test)]
pub mod codegen_float_method_return_inference_test;
#[cfg(test)]
pub mod codegen_for_loop_ownership_test;
#[cfg(test)]
pub mod codegen_format_macro_test;
#[cfg(test)]
pub mod codegen_forward_reference_limitation_test;
#[cfg(test)]
pub mod codegen_gameloop_ambiguity_test;
#[cfg(test)]
pub mod codegen_generics_comprehensive_tests;
#[cfg(test)]
pub mod codegen_glob_import_ambiguity_test;
#[cfg(test)]
pub mod codegen_hashmap_auto_borrow_test;
#[cfg(test)]
pub mod codegen_hashmap_comment_false_positive_test;
#[cfg(test)]
pub mod codegen_hashmap_remove_test;
#[cfg(test)]
pub mod codegen_helpers_test;
#[cfg(test)]
pub mod codegen_if_else_expr_in_assignment_test;
#[cfg(test)]
pub mod codegen_if_else_expression_test;
#[cfg(test)]
pub mod codegen_if_let_bound_variable_test;
#[cfg(test)]
pub mod codegen_if_let_expression_test;
#[cfg(test)]
pub mod codegen_if_let_method_call_test;
#[cfg(test)]
pub mod codegen_if_let_string_return_test;
#[cfg(test)]
pub mod codegen_import_alias_test;
#[cfg(test)]
pub mod codegen_index_element_type_test;
#[cfg(test)]
pub mod codegen_loops_comprehensive_tests;
#[cfg(test)]
pub mod codegen_main_in_lib_test;
#[cfg(test)]
pub mod codegen_match_arm_expression_vs_statement_test;
#[cfg(test)]
pub mod codegen_match_arm_ownership_test;
#[cfg(test)]
pub mod codegen_match_arm_semicolons_test;
#[cfg(test)]
pub mod codegen_match_arm_single_tuple_test;
#[cfg(test)]
pub mod codegen_match_comprehensive_tests;
#[cfg(test)]
pub mod codegen_method_call_arg_copy_type_test;
#[cfg(test)]
pub mod codegen_method_call_borrow_inconsistency_test;
#[cfg(test)]
pub mod codegen_method_call_clone_bug_test;
#[cfg(test)]
pub mod codegen_method_call_in_if_test;
#[cfg(test)]
pub mod codegen_method_call_on_variable_test;
#[cfg(test)]
pub mod codegen_method_call_syntax_test;
#[cfg(test)]
pub mod codegen_method_calls_comprehensive_tests;
#[cfg(test)]
pub mod codegen_module_string_coercion_test;
#[cfg(test)]
pub mod codegen_multiple_method_call_args_test;
#[cfg(test)]
pub mod codegen_nested_module_imports_test;
#[cfg(test)]
pub mod codegen_operators_test;
#[cfg(test)]
pub mod codegen_option_ref_return_test;
#[cfg(test)]
pub mod codegen_owned_param_field_assignment_test;
#[cfg(test)]
pub mod codegen_param_mutability_test;
#[cfg(test)]
pub mod codegen_param_passed_to_owned_function_test;
#[cfg(test)]
pub mod codegen_paren_precedence_test;
#[cfg(test)]
pub mod codegen_parent_module_reexport_test;
#[cfg(test)]
pub mod codegen_pattern_analysis_test;
#[cfg(test)]
pub mod codegen_property_test_imports_test;
#[cfg(test)]
pub mod codegen_pub_const_test;
#[cfg(test)]
pub mod codegen_pub_use_module_path_test;
#[cfg(test)]
pub mod codegen_qualified_call_string_literal_test;
#[cfg(test)]
pub mod codegen_qualified_struct_init_test;
#[cfg(test)]
pub mod codegen_ref_string_auto_clone_test;
#[cfg(test)]
pub mod codegen_ref_string_param_clone_test;
#[cfg(test)]
pub mod codegen_sibling_module_imports_test;
#[cfg(test)]
pub mod codegen_simd_vectorization_test;
#[cfg(test)]
pub mod codegen_str_to_string_test;
#[cfg(test)]
pub mod codegen_string_analysis_test;
#[cfg(test)]
pub mod codegen_string_comprehensive_tests;
#[cfg(test)]
pub mod codegen_string_extended_test;
#[cfg(test)]
pub mod codegen_string_literal_autoconvert_test;
#[cfg(test)]
pub mod codegen_string_param_ownership_test;
#[cfg(test)]
pub mod codegen_string_str_conversion_test;
#[cfg(test)]
pub mod codegen_struct_field_str_shorthand_test;
#[cfg(test)]
pub mod codegen_struct_init_fields_test;
#[cfg(test)]
pub mod codegen_struct_init_in_loop_test;
#[cfg(test)]
pub mod codegen_struct_pattern_shorthand_test;
#[cfg(test)]
pub mod codegen_test_attribute_test;
#[cfg(test)]
pub mod codegen_test_cases_string_inference_test;
#[cfg(test)]
pub mod codegen_trait_impl_method_call_args_test;
#[cfg(test)]
pub mod codegen_type_analysis_test;
#[cfg(test)]
pub mod codegen_unnecessary_parens_test;
#[cfg(test)]
pub mod codegen_unused_variable_prefix_test;
#[cfg(test)]
pub mod codegen_user_defined_fn_shadow_test;
#[cfg(test)]
pub mod codegen_usize_inference_test;
#[cfg(test)]
pub mod codegen_vec3_copy_no_ref_test;
#[cfg(test)]
pub mod codegen_vec_copy_struct_test;
#[cfg(test)]
pub mod codegen_vec_index_borrow_test;
#[cfg(test)]
pub mod codegen_vec_ref_push_test;
#[cfg(test)]
pub mod codegen_vec_remove_usize_test;
#[cfg(test)]
pub mod codegen_vec_string_context_test;
#[cfg(test)]
pub mod codegen_windjammer_ui_bugs_test;
#[cfg(test)]
pub mod collect_turbofish_test;
#[cfg(test)]
pub mod comparison_cast_removal_test;
#[cfg(test)]
pub mod comparison_int_vs_usize_test;
#[cfg(test)]
pub mod comparison_no_clone_test;
#[cfg(test)]
pub mod compiler_improvements_integration_test;
#[cfg(test)]
pub mod compiler_test;
#[cfg(test)]
pub mod compiler_tests;
#[cfg(test)]
pub mod compound_assign_int_no_float_cast_test;
#[cfg(test)]
pub mod compound_assign_test;
#[cfg(test)]
pub mod compound_assignment_f32_test;
#[cfg(test)]
pub mod compound_assignment_math_test;
#[cfg(test)]
pub mod compound_assignment_string_test;
#[cfg(test)]
pub mod compound_operators_test;
#[cfg(test)]
pub mod comprehensive_lexer_tests;
#[cfg(test)]
pub mod conformance_go_test;
#[cfg(test)]
pub mod conformance_interpreter_test;
#[cfg(test)]
pub mod conformance_js_test;
#[cfg(test)]
pub mod conformance_rust_test;
#[cfg(test)]
pub mod conformance_tests;
#[cfg(test)]
pub mod constant_folding_f32_test;
#[cfg(test)]
pub mod constructor_no_self_param_test;
#[cfg(test)]
pub mod constructor_type_inference_test;
#[cfg(test)]
pub mod copy_detection_generic_test;
#[cfg(test)]
pub mod copy_detection_vec_field_test;
#[cfg(test)]
pub mod copy_semantics_integration_test;
#[cfg(test)]
pub mod copy_semantics_test;
#[cfg(test)]
pub mod copy_tuple_pattern_binding_test;
#[cfg(test)]
pub mod copy_type_method_params_integration_test;
#[cfg(test)]
pub mod copy_type_no_clone_test;
#[cfg(test)]
pub mod copy_type_parameter_inference_test;
#[cfg(test)]
pub mod copy_type_passthrough_mut_test;
#[cfg(test)]
pub mod crate_imports_test;
#[cfg(test)]
pub mod crate_internal_not_extern_test;
#[cfg(test)]
pub mod crate_module_call_no_runtime_ffi_test;
pub mod cross_backend_conformance_harness;
#[cfg(test)]
pub mod cross_crate_string_literal_test;
#[cfg(test)]
pub mod cross_file_auto_borrow_call_site_test;
#[cfg(test)]
pub mod cross_file_copy_field_no_clone_test;
#[cfg(test)]
pub mod cross_file_fn_call_ref_arg_test;
#[cfg(test)]
pub mod cross_file_i32_subtraction_test;
#[cfg(test)]
pub mod cross_file_method_arg_passthrough_mut_test;
#[cfg(test)]
pub mod cross_file_mut_passthrough_call_site_test;
#[cfg(test)]
pub mod cross_file_ownership_meta_test;
#[cfg(test)]
pub mod cross_file_trait_impl_test;
#[cfg(test)]
pub mod cross_file_trait_inference_regeneration_test;
#[cfg(test)]
pub mod cross_module_copy_field_test;
#[cfg(test)]
pub mod cross_module_extern_unsafe_test;
#[cfg(test)]
pub mod cross_module_nested_field_mut_test;
#[cfg(test)]
pub mod cross_module_ordering_test;
#[cfg(test)]
pub mod cross_module_self_field_mut_test;
#[cfg(test)]
pub mod cross_module_struct_literal_test;
#[cfg(test)]
pub mod cross_type_method_mutation_test;
#[cfg(test)]
pub mod debug_module_leak;
#[cfg(test)]
pub mod declaration_stub_registry_test;
#[cfg(test)]
pub mod decorator_registry_test;
#[cfg(test)]
pub mod decorator_syntax_test;
#[cfg(test)]
pub mod dep_copy_struct_override_test;
#[cfg(test)]
pub mod deref_logic_layered_test;
#[cfg(test)]
pub mod dereference_inference_test;
#[cfg(test)]
pub mod derive_copy_tracking_test;
#[cfg(test)]
pub mod detect_rust_leakage_test;
#[cfg(test)]
pub mod doc_comment_after_derive_test;
#[cfg(test)]
pub mod doc_comment_impl_tests;
#[cfg(test)]
pub mod doc_comments_test;
#[cfg(test)]
pub mod dogfood_engine_ownership_test;
#[cfg(test)]
pub mod dogfooding_comprehensive_test;
#[cfg(test)]
pub mod dogfooding_fixes_match_collections_test;
#[cfg(test)]
pub mod dogfooding_fixes_self_iterator_test;
#[cfg(test)]
pub mod dogfooding_fixes_strings_ui_test;
#[cfg(test)]
pub mod double_clone_bug_test;
#[cfg(test)]
pub mod duplicate_impl_fn_test;
#[cfg(test)]
pub mod e0277_remaining_test;
#[cfg(test)]
pub mod e0308_builder_owned_self_receiver_test;
#[cfg(test)]
pub mod e0308_copy_scalar_ref_test;
#[cfg(test)]
pub mod e0308_expected_float_type_test;
#[cfg(test)]
pub mod e0308_float_unification_test;
#[cfg(test)]
pub mod e0308_if_let_void_semicolon_test;
#[cfg(test)]
pub mod e0308_index_deref_copy_param_test;
#[cfg(test)]
pub mod e0308_match_ref_enum_struct_literals_test;
#[cfg(test)]
pub mod e0308_systematic_test;
#[cfg(test)]
pub mod e0308_tuple_index_deref_test;
#[cfg(test)]
pub mod e0308_verify_pattern_a_test;
#[cfg(test)]
pub mod e0308_verify_pattern_b_test;
#[cfg(test)]
pub mod e0382_non_copy_multi_use_test;
#[cfg(test)]
pub mod e0432_submodule_crate_import_test;
#[cfg(test)]
pub mod e0507_final_elimination_test;
#[cfg(test)]
pub mod e0507_final_test;
#[cfg(test)]
pub mod e0507_option_if_let_mut_field_test;
#[cfg(test)]
pub mod e0507_ownership_inference_test;
#[cfg(test)]
pub mod e0507_self_borrow_tests;
#[cfg(test)]
pub mod e0507_systematic_test;
#[cfg(test)]
pub mod e0596_field_mutation_test;
#[cfg(test)]
pub mod e0596_inventory_complete_test;
#[cfg(test)]
pub mod e0599_generic_impl_clone_bound_test;
#[cfg(test)]
pub mod e0614_comprehensive_test;
#[cfg(test)]
pub mod e0614_entity_test;
#[cfg(test)]
pub mod e0614_final_elimination_test;
#[cfg(test)]
pub mod e0614_regression_fix_test;
#[cfg(test)]
pub mod e2e_comprehensive_tests;
#[cfg(test)]
pub mod early_return_test;
#[cfg(test)]
pub mod edge_case_errors_test;
#[cfg(test)]
pub mod eject_tests;
#[cfg(test)]
pub mod end_to_end_tests;
#[cfg(test)]
pub mod enhanced_javascript_tests;
#[cfg(test)]
pub mod enum_equality_usage_test;
#[cfg(test)]
pub mod enum_partial_eq_test;
#[cfg(test)]
pub mod enum_struct_destructuring_test;
#[cfg(test)]
pub mod enum_variant_method_call_test;
#[cfg(test)]
pub mod enum_variant_string_coercion_test;
#[cfg(test)]
pub mod error_messages_test;
#[cfg(test)]
pub mod explicit_deref_comparison_test;
#[cfg(test)]
pub mod explicit_deref_owned_param_test;
#[cfg(test)]
pub mod extended_mutation_detection_test;
#[cfg(test)]
pub mod extern_borrowed_string_test;
#[cfg(test)]
pub mod extern_fn_codegen_test;
#[cfg(test)]
pub mod extern_fn_declaration_test;
#[cfg(test)]
pub mod extern_fn_integration_test;
#[cfg(test)]
pub mod extern_fn_string_literal_test;
#[cfg(test)]
pub mod extern_fn_unsafe_test;
#[cfg(test)]
pub mod extern_fn_unsafe_wrapping_test;
#[cfg(test)]
pub mod extern_submodule_qualifier_test;
#[cfg(test)]
pub mod extern_unsafe_wrapping_test;
#[cfg(test)]
pub mod f32_f64_cast_explosion_test;
#[cfg(test)]
pub mod f32_f64_codegen_e0308_test;
#[cfg(test)]
pub mod feature_tests;
#[cfg(test)]
pub mod ffi_auto_mut_pointer_test;
#[cfg(test)]
pub mod ffi_extern_comprehensive_tests;
#[cfg(test)]
pub mod ffi_module_discovery_test;
#[cfg(test)]
pub mod ffi_module_test;
#[cfg(test)]
pub mod ffi_string_literal_arg_test;
#[cfg(test)]
pub mod field_array_indexing_i32_test;
#[cfg(test)]
pub mod field_chain_method_signature_test;
#[cfg(test)]
pub mod float_arithmetic_e0277_test;
#[cfg(test)]
pub mod float_comparison_final_test;
#[cfg(test)]
pub mod float_field_assignment_inference_test;
#[cfg(test)]
pub mod float_impl_method_test;
#[cfg(test)]
pub mod float_inference_array_vec_test;
#[cfg(test)]
pub mod float_inference_binary_op_lhs_test;
#[cfg(test)]
pub mod float_inference_chained_ops_test;
#[cfg(test)]
pub mod float_inference_collision_test;
#[cfg(test)]
pub mod float_inference_comparison_test;
#[cfg(test)]
pub mod float_inference_comprehensive_test;
#[cfg(test)]
pub mod float_inference_dt_consistency_test;
#[cfg(test)]
pub mod float_inference_duplicate_struct_basename_test;
#[cfg(test)]
pub mod float_inference_ffi_e0308_test;
#[cfg(test)]
pub mod float_inference_field_initializer_test;
#[cfg(test)]
pub mod float_inference_function_args_test;
#[cfg(test)]
pub mod float_inference_if_else_test;
#[cfg(test)]
pub mod float_inference_local_var_test;
#[cfg(test)]
pub mod float_inference_match_arms_test;
#[cfg(test)]
pub mod float_inference_parameter_tracking_test;
#[cfg(test)]
pub mod float_inference_physics_test;
#[cfg(test)]
pub mod float_inference_remaining_patterns_test;
#[cfg(test)]
pub mod float_inference_return_test;
#[cfg(test)]
pub mod float_inference_struct_fields_test;
#[cfg(test)]
pub mod float_inference_tuple_in_vec_push_test;
#[cfg(test)]
pub mod float_literal_inference_test;
#[cfg(test)]
pub mod float_match_arm_unification_test;
#[cfg(test)]
pub mod float_spurious_f64_cast_test;
#[cfg(test)]
pub mod float_struct_field_inference_test;
#[cfg(test)]
pub mod float_type_unification_test;
#[cfg(test)]
pub mod for_loop_borrow_inference_test;
#[cfg(test)]
pub mod for_loop_borrow_propagation_test;
#[cfg(test)]
pub mod for_loop_enumerate_borrow_test;
#[cfg(test)]
pub mod for_loop_mut_in_match_test;
#[cfg(test)]
pub mod for_loop_mut_iteration_test;
#[cfg(test)]
pub mod for_loop_wildcard_test;
#[cfg(test)]
pub mod forbidden_as_str_test;
#[cfg(test)]
pub mod function_args_3layer_test;
#[cfg(test)]
pub mod generic_owned_param_integration_test;
#[cfg(test)]
pub mod generic_type_propagation_test;
#[cfg(test)]
pub mod glob_import_struct_field_typing_test;
#[cfg(test)]
pub mod go_backend_extended_test;
#[cfg(test)]
pub mod go_backend_test;
#[cfg(test)]
pub mod go_enum_pattern_extraction_test;
#[cfg(test)]
pub mod hashmap_auto_borrow_test;
#[cfg(test)]
pub mod hashmap_copy_key_auto_borrow_test;
#[cfg(test)]
pub mod hashmap_get_deref_test;
#[cfg(test)]
pub mod hashmap_get_double_ref_test;
#[cfg(test)]
pub mod hashmap_get_mut_inference_test;
#[cfg(test)]
pub mod hashmap_vec_remove_ref_test;
#[cfg(test)]
pub mod i32_subtraction_no_cast_test;
#[cfg(test)]
pub mod if_else_expression_context_test;
#[cfg(test)]
pub mod if_else_expression_semicolons_test;
#[cfg(test)]
pub mod if_else_ownership_consistency_test;
#[cfg(test)]
pub mod if_else_parameter_return_test;
#[cfg(test)]
pub mod if_else_ref_literal_test;
#[cfg(test)]
pub mod if_else_string_consistency_test;
#[cfg(test)]
pub mod if_let_codegen_test;
#[cfg(test)]
pub mod if_let_string_consistency_test;
#[cfg(test)]
pub mod ignore_decorator_test;
#[cfg(test)]
pub mod immutability_enforcement_test;
#[cfg(test)]
pub mod impl_trait_param_test;
#[cfg(test)]
pub mod import_braced_dedup_test;
#[cfg(test)]
pub mod import_generation_comprehensive_test;
#[cfg(test)]
pub mod import_resolution_sibling_explicit_use_test;
#[cfg(test)]
pub mod incremental_rebuild_test;
#[cfg(test)]
pub mod index_suffix_usize_test;
#[cfg(test)]
pub mod inline_mod_extern_fn_integration_test;
#[cfg(test)]
pub mod int_float_arithmetic_complete_test;
#[cfg(test)]
pub mod int_float_arithmetic_comprehensive_test;
#[cfg(test)]
pub mod int_float_arithmetic_test;
#[cfg(test)]
pub mod int_float_copy_semantics_test;
#[cfg(test)]
pub mod int_float_nested_comprehensive_test;
#[cfg(test)]
pub mod int_float_ownership_integration_test;
#[cfg(test)]
pub mod int_float_real_patterns_test;
#[cfg(test)]
pub mod mcp_guardrails_test;
#[cfg(test)]
pub mod ide_analysis_test;
#[cfg(test)]
pub mod int_inference_assignment_and_len_test;
#[cfg(test)]
pub mod int_inference_binop_propagation_test;
#[cfg(test)]
pub mod int_inference_cast_collision_test;
#[cfg(test)]
pub mod int_inference_compound_assignment_test;
#[cfg(test)]
pub mod int_inference_generic_collections_test;
#[cfg(test)]
pub mod int_inference_parallel_merge_test;
#[cfg(test)]
pub mod int_inference_vec_element_test;
#[cfg(test)]
pub mod int_inference_vec_remove_usize_test;
#[cfg(test)]
pub mod int_to_usize_cast_test;
#[cfg(test)]
pub mod int_usize_bidirectional_test;
#[cfg(test)]
pub mod int_usize_comparison_test;
#[cfg(test)]
pub mod integration_backend_conformance_test;
#[cfg(test)]
pub mod integration_ffi_build_test;
#[cfg(test)]
pub mod integration_test_helpers_self_test;
#[cfg(test)]
pub mod interpreter_advanced_test;
#[cfg(test)]
pub mod interpreter_bugs_test;
#[cfg(test)]
pub mod interpreter_test;
#[cfg(test)]
pub mod iter_clone_push_test;
#[cfg(test)]
pub mod iter_field_copy_no_clone_test;
#[cfg(test)]
pub mod iter_inference_test;
#[cfg(test)]
pub mod iter_push_clone_test;
#[cfg(test)]
pub mod iter_ref_vs_owned_comparison_test;
#[cfg(test)]
pub mod iter_var_method_call_test;
#[cfg(test)]
pub mod js_backend_test;
#[cfg(test)]
pub mod language_consistency_test;
#[cfg(test)]
pub mod len_arithmetic_inference_test;
#[cfg(test)]
pub mod len_comparison_literal_test;
#[cfg(test)]
pub mod len_zero_comparison_test;
#[cfg(test)]
pub mod let_immutability_test;
#[cfg(test)]
pub mod lexer_tests;
#[cfg(test)]
pub mod lib_rs_regen_test;
#[cfg(test)]
pub mod lib_rs_subdirectory_prevention_test;
#[cfg(test)]
pub mod lib_vs_mod_generation_test;
#[cfg(test)]
pub mod lifetime_inference_test;
#[cfg(test)]
pub mod linter_test;
#[cfg(test)]
pub mod linter_tests;
#[cfg(test)]
pub mod literal_usize_cast_test;
#[cfg(test)]
pub mod local_var_auto_mut_test;
#[cfg(test)]
pub mod local_variable_shadowing_test;
#[cfg(test)]
pub mod loop_variable_ownership_test;
#[cfg(test)]
pub mod map_type_test;
#[cfg(test)]
pub mod match_arm_binding_method_call_test;
#[cfg(test)]
pub mod match_arm_comparison_test;
#[cfg(test)]
pub mod match_arm_format_test;
#[cfg(test)]
pub mod match_binding_iter_comparison_test;
#[cfg(test)]
pub mod match_bound_deref_test;
#[cfg(test)]
pub mod match_ergonomics_mut_self_test;
#[cfg(test)]
pub mod match_ergonomics_mut_test;
#[cfg(test)]
pub mod match_get_some_v_auto_deref_test;
#[cfg(test)]
pub mod match_string_return_test;
#[cfg(test)]
pub mod matches_macro_optimization_test;
#[cfg(test)]
pub mod memory_safety_tests;
#[cfg(test)]
pub mod method_arg_auto_ref_bug_test;
#[cfg(test)]
pub mod method_arg_conversion_test;
#[cfg(test)]
pub mod method_arg_no_spurious_mut_ref_test;
#[cfg(test)]
pub mod method_body_float_field_assignment_test;
#[cfg(test)]
pub mod method_call_clone_test;
#[cfg(test)]
pub mod method_call_f32_result_test;
#[cfg(test)]
pub mod method_call_reference_args_test;
#[cfg(test)]
pub mod method_call_string_args_test;
#[cfg(test)]
pub mod method_calls_3layer_test;
#[cfg(test)]
pub mod method_chain_string_test;
#[cfg(test)]
pub mod method_collision_mutation_test;
#[cfg(test)]
pub mod method_mutability_inference_test;
#[cfg(test)]
pub mod method_receiver_mut_inference_test;
#[cfg(test)]
pub mod method_receiver_ownership_test;
#[cfg(test)]
pub mod method_signature_lookup_integration_test;
#[cfg(test)]
pub mod method_string_arg_test;
#[cfg(test)]
pub mod mixed_int_float_arithmetic_test;
#[cfg(test)]
pub mod mixed_numeric_arithmetic_test;
#[cfg(test)]
pub mod mod_rs_auto_reexport_test;
#[cfg(test)]
pub mod mod_rs_self_path_test;
#[cfg(test)]
pub mod mod_wj_codegen_test;
#[cfg(test)]
pub mod module_declaration_bug_test;
#[cfg(test)]
pub mod module_declaration_integration_test;
#[cfg(test)]
pub mod module_declarations_test;
#[cfg(test)]
pub mod module_discovery_scope_test;
#[cfg(test)]
pub mod module_existence_test;
#[cfg(test)]
pub mod module_feature_gates_test;
#[cfg(test)]
pub mod module_imports_test;
#[cfg(test)]
pub mod module_qualified_signature_test;
#[cfg(test)]
pub mod module_reexport_generation_test;
#[cfg(test)]
pub mod module_resolution_rust_keywords_test;
#[cfg(test)]
pub mod module_system_comprehensive_tests;
#[cfg(test)]
pub mod module_system_e0432_test;
#[cfg(test)]
pub mod module_system_test;
#[cfg(test)]
pub mod module_tree_copying_test;
#[cfg(test)]
pub mod move_closure_tests;
#[cfg(test)]
pub mod multi_file_no_inline_modules_test;
#[cfg(test)]
pub mod multi_impl_trait_ownership_test;
#[cfg(test)]
pub mod multi_target_tests;
#[cfg(test)]
pub mod multiline_doc_comment_test;
#[cfg(test)]
pub mod mut_error_messages_test;
#[cfg(test)]
pub mod mut_self_via_field_method_test;
#[cfg(test)]
pub mod mutability_complete_test;
#[cfg(test)]
pub mod mutated_returned_ownership_test;
#[cfg(test)]
pub mod nested_field_access_ownership_test;
#[cfg(test)]
pub mod nested_field_borrow_iteration_test;
#[cfg(test)]
pub mod nested_field_no_intermediate_clone_test;
#[cfg(test)]
pub mod nested_generics_test;
#[cfg(test)]
pub mod nested_index_no_clone_test;
#[cfg(test)]
pub mod nested_module_import_test;
#[cfg(test)]
pub mod nested_module_output_path_test;
#[cfg(test)]
pub mod no_copy_with_drop_test;
#[cfg(test)]
pub mod no_inline_modules_in_files_test;
#[cfg(test)]
pub mod orphan_mod_cleanup_test;
#[cfg(test)]
pub mod out_of_scope_module_prevention_test;
#[cfg(test)]
pub mod owned_param_insert_clone_test;
#[cfg(test)]
pub mod owned_self_field_move_test;
#[cfg(test)]
pub mod ownership_binary_op_test;
#[cfg(test)]
pub mod ownership_copy_fixed_point_e0382_test;
#[cfg(test)]
pub mod ownership_copy_type_method_call_test;
#[cfg(test)]
pub mod ownership_deref_test;
#[cfg(test)]
pub mod ownership_edge_cases_final_test;
#[cfg(test)]
pub mod ownership_edge_cases_test;
#[cfg(test)]
pub mod ownership_external_crate_copy_test;
#[cfg(test)]
pub mod ownership_field_test;
#[cfg(test)]
pub mod ownership_final_cleanup_test;
#[cfg(test)]
pub mod ownership_inference_method_params_test;
#[cfg(test)]
pub mod ownership_inference_return_type_test;
#[cfg(test)]
pub mod ownership_inference_self_by_value_test;
#[cfg(test)]
pub mod ownership_integration_test;
#[cfg(test)]
pub mod ownership_method_params_test;
#[cfg(test)]
pub mod ownership_method_test;
#[cfg(test)]
pub mod ownership_missing_math_methods_test;
#[cfg(test)]
pub mod ownership_mutability_test;
#[cfg(test)]
pub mod ownership_option_pattern_test;
#[cfg(test)]
pub mod ownership_param_type_matches_return_test;
#[cfg(test)]
pub mod ownership_self_field_mutation_test;
#[cfg(test)]
pub mod ownership_tracker_bindings_api_test;
#[cfg(test)]
pub mod ownership_tracker_literals_ops_test;
#[cfg(test)]
pub mod ownership_tracker_methods_unary_test;
#[cfg(test)]
pub mod ownership_tracker_paths_test;
#[cfg(test)]
pub mod ownership_tracker_population_test;
#[cfg(test)]
pub mod ownership_transitive_mut_test;
#[cfg(test)]
pub mod param_ownership_multiple_use_test;
#[cfg(test)]
pub mod param_set_method_mut_test;
#[cfg(test)]
pub mod parent_directory_module_test;
#[cfg(test)]
pub mod parser_decorator_kwargs_test;
#[cfg(test)]
pub mod parser_decorator_with_expressions_test;
#[cfg(test)]
pub mod parser_error_line_numbers_test;
#[cfg(test)]
pub mod parser_expression_tests;
#[cfg(test)]
pub mod parser_item_tests;
#[cfg(test)]
pub mod parser_match_arm_assignment_test;
#[cfg(test)]
pub mod parser_match_block_comma_test;
#[cfg(test)]
pub mod parser_self_import_test;
#[cfg(test)]
pub mod parser_simple_imports_test;
#[cfg(test)]
pub mod parser_statement_tests;
#[cfg(test)]
pub mod parser_test_cases_decorator_test;
#[cfg(test)]
pub mod parser_type_tests;
#[cfg(test)]
pub mod partial_eq_registry_nested_test;
#[cfg(test)]
pub mod passthrough_owned_param_test;
#[cfg(test)]
pub mod passthrough_qualified_call_test;
#[cfg(test)]
pub mod pattern_binding_deref_codegen_test;
#[cfg(test)]
pub mod pattern_matching_tests;
#[cfg(test)]
pub mod platform_specific_modules_test;
#[cfg(test)]
pub mod playtest_harness_migration_bugs_test;
#[cfg(test)]
pub mod primitive_method_calls_test;
#[cfg(test)]
pub mod println_no_macro_test;
#[cfg(test)]
pub mod project_paths_source_root_test;
#[cfg(test)]
pub mod pub_use_codegen_test;
#[cfg(test)]
pub mod push_str_auto_borrow_test;
#[cfg(test)]
pub mod range_iteration_fix_test;
#[cfg(test)]
pub mod range_type_mismatch_test;
#[cfg(test)]
pub mod readonly_param_borrow_inference_test;
#[cfg(test)]
pub mod recursive_output_prevention_test;
#[cfg(test)]
pub mod recursive_readonly_self_test;
#[cfg(test)]
pub mod ref_mut_logic_layered_test;
#[cfg(test)]
pub mod ref_self_mut_upgrade_test;
#[cfg(test)]
pub mod ref_strip_owned_param_test;
#[cfg(test)]
pub mod reference_coercion_test;
#[cfg(test)]
pub mod reference_handling_test;
#[cfg(test)]
pub mod render_mut_self_inference_test;
#[cfg(test)]
pub mod repr_c_struct_layout_test;
#[cfg(test)]
pub mod return_optimization_if_without_else_test;
#[cfg(test)]
pub mod return_statement_optimization_test;
#[cfg(test)]
pub mod return_statement_test;
#[cfg(test)]
pub mod return_string_literal_test;
#[cfg(test)]
pub mod return_usize_to_int_cast_test;
#[cfg(test)]
pub mod runtime_ffi_import_bug_test;
#[cfg(test)]
pub mod rust_coercion_rules_test;
#[cfg(test)]
pub mod rust_integration_tests_auto_register_test;
#[cfg(test)]
pub mod rust_leakage_clone_warning_test;
#[cfg(test)]
pub mod rust_str_string_semantics_verification;
#[cfg(test)]
pub mod same_name_module_bug_test;
#[cfg(test)]
pub mod same_name_regeneration_bug_test;
#[cfg(test)]
pub mod scientific_notation_test;
#[cfg(test)]
pub mod self_borrow_temp_extraction_test;
#[cfg(test)]
pub mod self_consuming_ownership_test;
#[cfg(test)]
pub mod self_copy_field_return_test;
#[cfg(test)]
pub mod self_field_binary_test;
#[cfg(test)]
pub mod self_field_method_mutation_test;
#[cfg(test)]
pub mod self_field_mutation_recursion_test;
#[cfg(test)]
pub mod self_no_access_test;
#[cfg(test)]
pub mod self_parameter_inference_test;
#[cfg(test)]
pub mod self_read_only_borrow_inference_test;
#[cfg(test)]
pub mod self_readonly_method_inference_test;
#[cfg(test)]
pub mod shader_exclusion_test;
#[cfg(test)]
pub mod shader_file_detection_test;
#[cfg(test)]
pub mod shader_wjsl_test;
#[cfg(test)]
pub mod sibling_module_imports_test;
#[cfg(test)]
pub mod single_file_binary_test;
#[cfg(test)]
pub mod source_map_portability_test;
#[cfg(test)]
pub mod source_map_portable_test;
#[cfg(test)]
pub mod statement_expression_fix_test;
#[cfg(test)]
pub mod static_helper_borrow_inference_test;
#[cfg(test)]
pub mod static_method_inference_integration_test;
#[cfg(test)]
pub mod static_method_not_enum_variant_test;
#[cfg(test)]
pub mod static_method_passthrough_ownership_test;
#[cfg(test)]
pub mod std_fs_codegen_test;
#[cfg(test)]
pub mod std_ops_import_integration_test;
#[cfg(test)]
pub mod stdlib_collections_lint_test;
#[cfg(test)]
pub mod stdlib_traits_cache_test;
#[cfg(test)]
pub mod str_ref_callsite_method_arg_test;
#[cfg(test)]
pub mod str_stored_in_owned_container_test;
#[cfg(test)]
pub mod str_string_codegen_test;
#[cfg(test)]
pub mod str_string_hashmap_test;
#[cfg(test)]
pub mod str_string_integration_test;
#[cfg(test)]
pub mod stress_test_large_codebase;
#[cfg(test)]
pub mod string_auto_borrow_test;
#[cfg(test)]
pub mod string_borrow_inference_integration_test;
#[cfg(test)]
pub mod string_comparison_borrowed_param_test;
#[cfg(test)]
pub mod string_comparison_test;
#[cfg(test)]
pub mod string_handling_tests;
#[cfg(test)]
pub mod string_interpolation_test;
#[cfg(test)]
pub mod string_literal_auto_owned_test;
#[cfg(test)]
pub mod string_literal_borrowed_param_test;
#[cfg(test)]
pub mod string_literal_enum_test;
#[cfg(test)]
pub mod string_literal_if_else_test;
#[cfg(test)]
pub mod string_literal_inference_test;
#[cfg(test)]
pub mod string_literal_method_call_test;
#[cfg(test)]
pub mod string_literal_method_chain_test;
#[cfg(test)]
pub mod string_literal_method_coercion_test;
#[cfg(test)]
pub mod string_literal_no_conversion_test;
#[cfg(test)]
pub mod string_literal_static_method_call_borrow_test;
#[cfg(test)]
pub mod string_literal_struct_constructor_test;
#[cfg(test)]
pub mod string_match_no_as_str_test;
#[cfg(test)]
pub mod string_method_call_test;
#[cfg(test)]
pub mod string_optimization_phase2_test;
#[cfg(test)]
pub mod string_optimization_phase3_test;
#[cfg(test)]
pub mod string_ownership_inference_test;
#[cfg(test)]
pub mod string_ownership_test;
#[cfg(test)]
pub mod string_parameter_ownership_bug_test;
#[cfg(test)]
pub mod string_parameter_ownership_test;
#[cfg(test)]
pub mod string_ref_param_test;
#[cfg(test)]
pub mod string_type_unification_test;
#[cfg(test)]
pub mod string_var_method_test;
#[cfg(test)]
pub mod struct_constructor_args_test;
#[cfg(test)]
pub mod struct_field_auto_borrow_test;
#[cfg(test)]
pub mod struct_field_if_else_string_test;
#[cfg(test)]
pub mod struct_field_literal_typing_test;
#[cfg(test)]
pub mod struct_registry_duplicate_names_test;
#[cfg(test)]
pub mod struct_some_string_test;
#[cfg(test)]
pub mod struct_to_bytes_auto_derive_test;
#[cfg(test)]
pub mod struct_visibility_test;
#[cfg(test)]
pub mod sub_object_mut_method_test;
#[cfg(test)]
pub mod super_import_flattening_test;
#[cfg(test)]
pub mod svo_bfs_layout_test;
#[cfg(test)]
pub mod svo_shader_compat_test;
#[cfg(test)]
pub mod test_cases_generation_test;
#[cfg(test)]
pub mod test_cli_exports;
#[cfg(test)]
pub mod test_cross_crate_float_inference;
#[cfg(test)]
pub mod test_cross_file_float_inference;
#[cfg(test)]
pub mod test_cross_file_int_inference;
#[cfg(test)]
pub mod test_cross_file_transitive_mutability;
#[cfg(test)]
pub mod test_float_backward_propagation;
#[cfg(test)]
pub mod test_float_function_param_propagation;
#[cfg(test)]
pub mod test_float_inference_field_assignment;
#[cfg(test)]
pub mod test_float_inference_function_args;
#[cfg(test)]
pub mod test_float_inference_module_aggregation;
#[cfg(test)]
pub mod test_float_inference_multi_file;
#[cfg(test)]
pub mod test_float_type_propagation;
#[cfg(test)]
pub mod test_framework_ffi_dependencies_test;
#[cfg(test)]
pub mod test_framework_game_tests_test;
#[cfg(test)]
pub mod test_framework_lib_generation_test;
#[cfg(test)]
pub mod test_framework_lib_name_test;
#[cfg(test)]
pub mod test_framework_library_deps_test;
#[cfg(test)]
pub mod test_framework_library_import_test;
#[cfg(test)]
pub mod test_framework_module_conflict_test;
#[cfg(test)]
pub mod test_library_preserve_structure;
#[cfg(test)]
pub mod test_method_signature_inference;
#[cfg(test)]
pub mod test_module_auto_discovery_test;
#[cfg(test)]
pub mod test_module_path_generation;
#[cfg(test)]
pub mod test_parser_warnings;
#[cfg(test)]
pub mod test_runner_library_detection_test;
#[cfg(test)]
pub mod test_transitive_mutability_inference;
#[cfg(test)]
pub mod test_wjsl_array_indexing;
#[cfg(test)]
pub mod test_wjsl_bitwise_ops;
#[cfg(test)]
pub mod test_wjsl_body_preservation;
#[cfg(test)]
pub mod test_wjsl_codegen;
#[cfg(test)]
pub mod test_wjsl_error_messages;
#[cfg(test)]
pub mod test_wjsl_let_mut;
#[cfg(test)]
pub mod test_wjsl_parser;
#[cfg(test)]
pub mod test_wjsl_shr_body;
#[cfg(test)]
pub mod trait_auto_borrow_test;
#[cfg(test)]
pub mod trait_auto_derive_merge_test;
#[cfg(test)]
pub mod trait_bound_inference_test;
#[cfg(test)]
pub mod trait_copy_param_integration_test;
#[cfg(test)]
pub mod trait_cross_file_mut_preserved_test;
#[cfg(test)]
pub mod trait_derivation_recursive_test;
#[cfg(test)]
pub mod trait_double_ref_bug_test;
#[cfg(test)]
pub mod trait_explicit_mut_preserved_test;
#[cfg(test)]
pub mod trait_impl_cross_file_self_ownership_test;
#[cfg(test)]
pub mod trait_impl_inherent_method_name_collision_test;
#[cfg(test)]
pub mod trait_impl_multi_file_test;
#[cfg(test)]
pub mod trait_impl_operator_copy_type_test;
#[cfg(test)]
pub mod trait_impl_ownership_test;
#[cfg(test)]
pub mod trait_impl_self_inference_test;
#[cfg(test)]
pub mod trait_impl_self_mutation_test;
#[cfg(test)]
pub mod trait_impl_self_param_test;
#[cfg(test)]
pub mod trait_impl_signature_match_test;
#[cfg(test)]
pub mod trait_impl_signature_matching_test;
#[cfg(test)]
pub mod trait_impl_syntax_test;
#[cfg(test)]
pub mod trait_method_default_impl_self_test;
#[cfg(test)]
pub mod trait_method_mutability_inference;
#[cfg(test)]
pub mod trait_method_no_body_test;
#[cfg(test)]
pub mod trait_method_no_inference_test;
#[cfg(test)]
pub mod trait_method_ownership_inference_test;
#[cfg(test)]
pub mod trait_method_self_param_inference_test;
#[cfg(test)]
pub mod trait_method_signature_edge_cases_test;
#[cfg(test)]
pub mod trait_object_derive_test;
#[cfg(test)]
pub mod trait_owned_self_render_test;
#[cfg(test)]
pub mod trait_regen_module_leak_test;
#[cfg(test)]
pub mod tryop_ownership_inference_test;
#[cfg(test)]
pub mod tuple_field_access_test;
#[cfg(test)]
pub mod tuple_struct_test;
#[cfg(test)]
pub mod type_alias_test;
#[cfg(test)]
pub mod type_coercion_test;
#[cfg(test)]
pub mod type_comparison_inference_test;
#[cfg(test)]
pub mod type_inference_ambiguity_test;
#[cfg(test)]
pub mod type_inference_binary_op_propagation_test;
#[cfg(test)]
pub mod type_inference_comparison_with_fields_test;
#[cfg(test)]
pub mod type_inference_compound_expression_test;
#[cfg(test)]
pub mod type_inference_const_fold_test;
#[cfg(test)]
pub mod type_inference_cross_module_test;
#[cfg(test)]
pub mod type_inference_division_literal_test;
#[cfg(test)]
pub mod type_inference_field_access_binary_op_test;
#[cfg(test)]
pub mod type_inference_field_access_test;
#[cfg(test)]
pub mod type_inference_field_in_binary_op_test;
#[cfg(test)]
pub mod type_inference_float_astar_pattern_test;
#[cfg(test)]
pub mod type_inference_float_method_call_test;
#[cfg(test)]
pub mod type_inference_float_test;
#[cfg(test)]
pub mod type_inference_for_loop_test;
#[cfg(test)]
pub mod type_inference_function_call_return_test;
#[cfg(test)]
pub mod type_inference_function_params_test;
#[cfg(test)]
pub mod type_inference_hashmap_insert_test;
#[cfg(test)]
pub mod type_inference_if_else_arms_test;
#[cfg(test)]
pub mod type_inference_mat4_inverse_test;
#[cfg(test)]
pub mod type_inference_match_arm_astar_pattern_test;
#[cfg(test)]
pub mod type_inference_match_arm_test;
#[cfg(test)]
pub mod type_inference_match_arm_unification_test;
#[cfg(test)]
pub mod type_inference_match_in_let_test;
#[cfg(test)]
pub mod type_inference_match_wildcard_test;
#[cfg(test)]
pub mod type_inference_math_constants_test;
#[cfg(test)]
pub mod type_inference_method_chain_test;
#[cfg(test)]
pub mod type_inference_method_return_binary_op_test;
#[cfg(test)]
pub mod type_inference_mixed_float_binary_ops_test;
#[cfg(test)]
pub mod type_inference_return_to_var_test;
#[cfg(test)]
pub mod type_inference_struct_field_test;
#[cfg(test)]
pub mod type_inference_struct_in_loop_test;
#[cfg(test)]
pub mod type_inference_vec3_f32_test;
#[cfg(test)]
pub mod type_inference_vec_push_test;
#[cfg(test)]
pub mod type_registry_full_test;
#[cfg(test)]
pub mod type_registry_integration_test;
#[cfg(test)]
pub mod type_registry_method_lookup_test;
#[cfg(test)]
pub mod types_equal_generic_test;
#[cfg(test)]
pub mod u32_literal_inference_test;
#[cfg(test)]
pub mod unit_struct_test;
#[cfg(test)]
pub mod unknown_method_mut_inference_test;
#[cfg(test)]
pub mod unused_field_test;
#[cfg(test)]
pub mod use_crate_path_integration_test;
#[cfg(test)]
pub mod user_copy_type_no_clone_test;
#[cfg(test)]
pub mod usize_comparison_casting_test;
#[cfg(test)]
pub mod usize_comparison_test;
#[cfg(test)]
pub mod usize_i32_cast_test;
#[cfg(test)]
pub mod vec3_no_spurious_cast_test;
#[cfg(test)]
pub mod vec_capacity_usize_test;
#[cfg(test)]
pub mod vec_copy_element_deref_test;
#[cfg(test)]
pub mod vec_get_ref_test;
#[cfg(test)]
pub mod vec_index_clone_test;
#[cfg(test)]
pub mod vec_index_context_test;
#[cfg(test)]
pub mod vec_index_if_expr_clone_test;
#[cfg(test)]
pub mod vec_index_struct_literal_auto_clone_test;
#[cfg(test)]
pub mod vec_indexing_borrow_test;
#[cfg(test)]
pub mod vec_indexing_ownership_test;
#[cfg(test)]
pub mod vec_owned_vs_ref_deref_test;
#[cfg(test)]
pub mod vec_push_copy_type_test;
#[cfg(test)]
pub mod vec_remove_integer_literal_test;
#[cfg(test)]
pub mod vec_remove_usize_no_ref_test;
#[cfg(test)]
pub mod vec_repeat_syntax_test;
#[cfg(test)]
pub mod void_return_semicolon_test;
#[cfg(test)]
pub mod voxel_grid_test;
#[cfg(test)]
pub mod voxel_meshing_test;
#[cfg(test)]
pub mod voxel_octree_test;
#[cfg(test)]
pub mod wgsl_advanced_test;
#[cfg(test)]
pub mod wgsl_basic_test;
#[cfg(test)]
pub mod wgsl_bindings_test;
#[cfg(test)]
pub mod wgsl_decorator_test;
#[cfg(test)]
pub mod wgsl_dogfood_test;
#[cfg(test)]
pub mod wgsl_entry_points_test;
#[cfg(test)]
pub mod wgsl_structs_test;
#[cfg(test)]
pub mod wgsl_type_safety_test;
#[cfg(test)]
pub mod wgsl_uniform_type_safety;
#[cfg(test)]
pub mod wgsl_vertex_fragment_test;
#[cfg(test)]
pub mod windjammer_fixtures_integration;
#[cfg(test)]
pub mod wjsl_assignment_parsing_test;
#[cfg(test)]
pub mod wjsl_assignment_test;
#[cfg(test)]
pub mod wjsl_atmosphere_shader_test;
#[cfg(test)]
pub mod wjsl_auto_binding_test;
#[cfg(test)]
pub mod wjsl_bloom_shader_test;
#[cfg(test)]
pub mod wjsl_const_decl_test;
#[cfg(test)]
pub mod wjsl_control_flow_scoping;
#[cfg(test)]
pub mod wjsl_denoise_quality_test;
#[cfg(test)]
pub mod wjsl_field_assignment_test;
#[cfg(test)]
pub mod wjsl_fire_shader_test;
#[cfg(test)]
pub mod wjsl_game_shaders_test;
#[cfg(test)]
pub mod wjsl_heat_distortion_test;
#[cfg(test)]
pub mod wjsl_hud_overlay_test;
#[cfg(test)]
pub mod wjsl_if_assignment_test;
#[cfg(test)]
pub mod wjsl_if_expression_test;
#[cfg(test)]
pub mod wjsl_include_test;
#[cfg(test)]
pub mod wjsl_less_than_comparison_test;
#[cfg(test)]
pub mod wjsl_let_mut_loop_test;
#[cfg(test)]
pub mod wjsl_let_mut_test;
#[cfg(test)]
pub mod wjsl_lighting_ao_test;
#[cfg(test)]
pub mod wjsl_lighting_quality_test;
#[cfg(test)]
pub mod wjsl_lighting_transpile_test;
#[cfg(test)]
pub mod wjsl_matrix_constructor_test;
#[cfg(test)]
pub mod wjsl_nested_generics_test;
#[cfg(test)]
pub mod wjsl_particle_shader_test;
#[cfg(test)]
pub mod wjsl_shader_regressions;
#[cfg(test)]
pub mod wjsl_svo64_traversal_test;
#[cfg(test)]
pub mod wjsl_volumetric_smoke_test;
#[cfg(test)]
pub mod wjsl_water_shader_test;
#[cfg(test)]
pub mod wjsl_workgroup_size_2arg_test;
#[cfg(test)]
pub mod wjsl_workgroup_var_test;

// Helper re-exports for test modules
pub use cross_backend_conformance_harness::*;
