#![cfg(any(
    not(any(
        feature = "parser_tests",
        feature = "analyzer_tests",
        feature = "codegen_tests",
        feature = "interpreter_tests",
        feature = "conformance_tests",
        feature = "integration_tests",
    )),
    feature = "parser_tests",
))]

#[path = "common/wjsl_shader_fixtures.rs"]
mod wjsl_shader_fixtures;


// TDD: Auto-generated WJSL binding preamble from ShaderGraph metadata.
//
// Tests that binding metadata produces valid WJSL declarations that
// can be prepended to a shader body and transpiled successfully.

use std::path::Path;

#[test]
fn test_auto_generated_preamble_transpiles() {
    // Simulate what ShaderGraph would generate for the atmosphere pass:
    // binding 0: uniform params: AtmosphereParams
    // binding 1: uniform camera: CameraUniforms
    // binding 2: storage read gbuffer: array<f32>
    // binding 3: storage read_write color_output: array<vec4<f32>>
    let preamble = r#"
@group(0) @binding(0) uniform params: AtmosphereParams;
@group(0) @binding(1) uniform camera: CameraUniforms;
@group(0) @binding(2) storage read gbuffer: array<f32>;
@group(0) @binding(3) storage read_write color_output: array<f32>;
"#;

    let body = r#"
struct AtmosphereParams {
    sun_direction: vec3<f32>,
    _pad: f32,
}

struct CameraUniforms {
    position: vec3<f32>,
    _pad1: f32,
    screen_size: vec2<f32>,
    near_plane: f32,
    far_plane: f32,
}

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
    let width = u32(camera.screen_size.x);
    let height = u32(camera.screen_size.y);
    if (id.x >= width || id.y >= height) { return; }
    let idx = id.y * width + id.x;
    color_output[idx] = 0.5;
}
"#;

    let full_source = format!("{}\n{}", preamble, body);
    let result = windjammer::wjsl::transpile_wjsl(&full_source);
    assert!(
        result.is_ok(),
        "Auto-generated preamble + body should transpile: {:?}",
        result.err()
    );

    let wgsl = result.unwrap();
    assert!(wgsl.contains("@binding(0)"), "Should have binding 0");
    assert!(wgsl.contains("@binding(1)"), "Should have binding 1");
    assert!(wgsl.contains("@binding(2)"), "Should have binding 2");
    assert!(wgsl.contains("@binding(3)"), "Should have binding 3");
}

#[test]
fn test_preamble_with_includes_transpiles() {
    let shader_dir = wjsl_shader_fixtures::shader_fixtures_dir();

    // Body-only shader (bindings would be auto-generated by ShaderGraph)
    let body_only = r#"
#include "wjsl_std/camera.wjsl"

struct MyParams {
    time: f32,
    intensity: f32,
    _pad: vec2<f32>,
}

@group(0) @binding(0) uniform params: MyParams;
@group(0) @binding(1) uniform camera: CameraUniforms;
@group(0) @binding(2) storage read_write output: array<f32>;

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
    let width = u32(camera.screen_size.x);
    let height = u32(camera.screen_size.y);
    if (id.x >= width || id.y >= height) { return; }
    let idx = id.y * width + id.x;
    output[idx] = params.intensity * params.time;
}
"#;

    let result = windjammer::wjsl::transpile_wjsl_with_includes(body_only, &shader_dir);
    assert!(
        result.is_ok(),
        "Shader with #include and bindings should transpile: {:?}",
        result.err()
    );
}

#[test]
fn test_binding_preamble_format() {
    // Verify the format of generated binding lines
    let line_uniform = "@group(0) @binding(0) uniform params: AtmosphereParams;";
    let line_storage_read = "@group(0) @binding(1) storage read gbuffer: array<f32>;";
    let line_storage_write = "@group(0) @binding(2) storage read_write output: array<f32>;";

    // These are valid WJSL - they should parse individually
    let source = format!(
        "{}\n{}\n{}\n\nstruct AtmosphereParams {{ time: f32, _pad: vec3<f32>, }}\n\n@compute @workgroup_size(1, 1, 1)\nfn main(@builtin(global_invocation_id) id: vec3<u32>) {{}}\n",
        line_uniform, line_storage_read, line_storage_write
    );

    let result = windjammer::wjsl::transpile_wjsl(&source);
    assert!(
        result.is_ok(),
        "Binding preamble format should be valid WJSL: {:?}",
        result.err()
    );
}
