/**
 * WASM Loader for Windjammer Editor
 * 
 * This module loads the Windjammer WASM module and provides
 * a JavaScript API for interacting with the game engine.
 */

let wasmModule = null;
let gameEngine = null;
let animationFrameId = null;
let lastFrameTime = performance.now();

/**
 * Initialize the WASM module
 */
export async function initWasm() {
    try {
        console.log('🚀 Loading Windjammer WASM module...');
        
        // Import the WASM module
        // Note: This path will be generated by wasm-pack
        wasmModule = await import('./pkg/windjammer_editor_web.js');
        
        console.log('✅ WASM module loaded successfully!');
        return wasmModule;
    } catch (error) {
        console.error('❌ Failed to load WASM module:', error);
        throw error;
    }
}

/**
 * Create a new game engine instance
 * @param {HTMLCanvasElement} canvas - The canvas element to render to
 */
export function createGameEngine(canvas) {
    if (!wasmModule) {
        throw new Error('WASM module not initialized. Call initWasm() first.');
    }
    
    try {
        gameEngine = new wasmModule.GameEngine(canvas);
        console.log('✅ Game engine created!');
        return gameEngine;
    } catch (error) {
        console.error('❌ Failed to create game engine:', error);
        throw error;
    }
}

/**
 * Start the game engine and begin the render loop
 */
export function startGameEngine() {
    if (!gameEngine) {
        throw new Error('Game engine not created. Call createGameEngine() first.');
    }
    
    gameEngine.start();
    startRenderLoop();
}

/**
 * Stop the game engine and cancel the render loop
 */
export function stopGameEngine() {
    if (!gameEngine) {
        return;
    }
    
    gameEngine.stop();
    stopRenderLoop();
}

/**
 * Reset the game engine
 */
export function resetGameEngine() {
    if (!gameEngine) {
        return;
    }
    
    gameEngine.reset();
}

/**
 * Start the render loop
 */
function startRenderLoop() {
    if (animationFrameId !== null) {
        return; // Already running
    }
    
    lastFrameTime = performance.now();
    
    function renderFrame(currentTime) {
        const deltaTime = currentTime - lastFrameTime;
        lastFrameTime = currentTime;
        
        // Update the game engine
        if (gameEngine && gameEngine.is_running()) {
            gameEngine.update(deltaTime);
        }
        
        // Continue the loop
        animationFrameId = requestAnimationFrame(renderFrame);
    }
    
    animationFrameId = requestAnimationFrame(renderFrame);
    console.log('🎬 Render loop started');
}

/**
 * Stop the render loop
 */
function stopRenderLoop() {
    if (animationFrameId !== null) {
        cancelAnimationFrame(animationFrameId);
        animationFrameId = null;
        console.log('⏸️ Render loop stopped');
    }
}

/**
 * Create a new scene
 * @param {string} name - The name of the scene
 */
export function createScene(name) {
    if (!wasmModule) {
        throw new Error('WASM module not initialized. Call initWasm() first.');
    }
    
    return new wasmModule.Scene(name);
}

/**
 * Create a new entity
 * @param {number} id - The entity ID
 * @param {string} name - The entity name
 */
export function createEntity(id, name) {
    if (!wasmModule) {
        throw new Error('WASM module not initialized. Call initWasm() first.');
    }
    
    return new wasmModule.Entity(id, name);
}

/**
 * Get the current game engine instance
 */
export function getGameEngine() {
    return gameEngine;
}

/**
 * Get the WASM module
 */
export function getWasmModule() {
    return wasmModule;
}

/**
 * Check if the WASM module is loaded
 */
export function isWasmLoaded() {
    return wasmModule !== null;
}

/**
 * Check if the game engine is running
 */
export function isEngineRunning() {
    return gameEngine !== null && gameEngine.is_running();
}

/**
 * Get the current frame count
 */
export function getFrameCount() {
    return gameEngine ? gameEngine.frame_count() : 0;
}

// Export all functions as a single object for convenience
export default {
    initWasm,
    createGameEngine,
    startGameEngine,
    stopGameEngine,
    resetGameEngine,
    createScene,
    createEntity,
    getGameEngine,
    getWasmModule,
    isWasmLoaded,
    isEngineRunning,
    getFrameCount,
};

