[package]
name = "{{PROJECT_NAME}}"
version = "0.1.0"
edition = "2025"

[dependencies]
# HTTP and async support (auto-included via std.http)
# reqwest = "0.11"
# tokio = { version = "1", features = ["full"] }

# JSON serialization (auto-included via std.json)
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"

# Add your additional dependencies here

[dev-dependencies]

[profile.release]
opt-level = 3
lto = true

