[package]
name = "windjammer-output"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"

[[bin]]
name = "windjammer-output"
path = "main.rs"
